### ISSUE TITLE
Back-End database and explorer

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#1]
**original post by @m-mohr:**

Create a centralized database that allows users to explore back-ends.

It should allow to get information and filter by:
* general information, e.g. version, costs, provider, ...
* data sets (image collections / products / ...): Should be in line with our get_data process and the filtering abilities. Back-ends provide this data at `/data`.
* processes: Easiest solution would probably be to allow users to send process graphs to the hub and extracts all required processes and arguments. Based on this can check against all back-ends and return only those back-ends providing the processes to execute the process graph.
* UDF capabilities, e.g. programming environments, libraries, ...

Back-end providers should be allowed to add their back-ends using an UI and the hub should automatically retrieve all relevant data from the API.

---

**task list compiled out of it by @christophfriedrich:**

- It should allow to filter backends by:
  - [x] general information, e.g.
    - [x] version,
    - [x] costs, *("with free plan only" option exists, but more is certainly possible)*
    - [x] provider *(is this even included in `/` metadata? :thinking:)*
  - [x] collections
  - [x] processes
  - [x] send process graphs to the hub and extract all
    - [x] required processes and
    - [ ] arguments, *(more validation should be added)*
    - [x] required collections
  - [x] output formats
  - [x] service types
  - [ ] UDF capabilities, e.g. programming environments, libraries, ... *(depends on API evolution)*
- Search across backends for:
  - collections
    - [x] with search results in name, title or description
    - [x] covering a certain spatial extent
    - [x] covering a certain temporal extent
    - [ ] with keywords
  - processes
    - [x] with search results in name, summary or description
    - [x] with matching parameter names/descriptions
    - [x] that are not deprecated
- Other functionality:
  - [ ] Back-end providers should be allowed to add their back-ends using an UI *(planned)*
  - [x] the hub should automatically retrieve all relevant data from the API

**Comment by christophfriedrich** [comment]
The first version of the hub concentrates on the functionalities mentioned in this issue. Major things listed here have already been implemented.

Converting the above to a task list and adding a few things that were implemented additionally:

It should allow to filter backends by:
- [x] general information, e.g.
  - [x] version,
  - [ ] costs, *("with free plan only" option exists, but more is certainly possible)*
  - [ ] provider *(is this even included in `/` metadata? :thinking:)*
- [x] collections
- [x] processes
- [x] send process graphs to the hub and extracts all
  - [x] required processes and
  - [ ] arguments, *(more validation should be added)*
  - [x] required collections
- [x] output formats
- [x] service types
- [ ] UDF capabilities, e.g. programming environments, libraries, ... *(depends on API evolution)*

Search across backends for:
- collections
  - [x] with search results in name, title or description
  - [x] covering a certain spatial extent
  - [x] covering a certain temporal extent
- processes
  - [x] with search results in name, summary or description
  - [x] with matching parameter names/descriptions
  - [x] that are not deprecated

Other functionality:
- [ ] Back-end providers should be allowed to add their back-ends using an UI *(planned)*
- [x] the hub should automatically retrieve all relevant data from the API

**Comment by m-mohr** [comment]
Most features have been implemented. Important task have been migrated to other issues.
