### ISSUE TITLE
openEO API changes

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-hub#67]
This is an issue to track changes to the openEO API that have relevance for the Hub:
- [x] The `production` fields default to `false` instead of `true` from after 1.0 RC2 (the next version of the migrations take care of this, but not sure whether the Hub implementation runs it beforehand)

Probably covered by Vue components and need no change here, but for completeness:
- [ ] `GET /udf_runtimes`: Added optional `title` property for UDF runtimes. [#266](https://github.com/Open-EO/openeo-api/issues/266)
- [ ] `GET /service_types`: Added optional `title` and `description` properties for service types. [#266](https://github.com/Open-EO/openeo-api/issues/266)
- [ ] `GET /file_formats`: Added optional `description` property for file formats. [#266](https://github.com/Open-EO/openeo-api/issues/266)

**Comment by christophfriedrich** [comment]
> default to `false` instead of `true`

At first I thought "srsly...?" But `false` is the better choice, so good that it's fixed. Thanks for the heads-up :+1:

**Comment by m-mohr** [comment]
Yeah, we went probably through the same thoughts :-)

**Comment by christophfriedrich** [comment]
Any changes in `GET /udf_runtimes` kinda fall under #28 as there's no support for UDF information yet at all.

Are there any instances with which I can test the changes in the service types and file formats endpoints?

**Comment by christophfriedrich** [comment]
> Are there any instances with which I can test the changes in the service types and file formats endpoints?

@m-mohr?
I'm pretty sure there shouldn't be any issues, but if there's something to test with I'm happy to do that testing, just in case.

**Comment by m-mohr** [comment]
You have the better overview over the available services and if any of them supports it already (I don't think so). ;-)

**Comment by christophfriedrich** [comment]
> You have the better overview

True, now that you've said it, I realise I'm actually right at the source :sweat_smile:

I had a look through the Hub's database: The additional fields you mentioned above are not yet used by anyone.
